### PR TITLE
ISSUE-116: Upgrade to the latest angular material release

### LINKED ISSUE #116: Upgrade to the latest Angular Material.

### PR DESCRIPTION
**Pull request by mcacek**
Upgrade to latest material release and cleanup layouts.

Resolves #116

### CODE REVIEW

**Comment by DSchau** [comment]
Looks like the tests failed due to a node-sass issue. I'm not that familiar with circle ci, but typically just re-starting the build fixes that issue

**Comment by DSchau** [comment]
Unfortunately, I don't think I can do that 😪

**Comment by mcacek** [comment]
Yeah, I think it has to do with caching of dependencies so I relaunched the build without cache.

**Comment by DSchau** [comment]
@mcacek looking like -> http://stackoverflow.com/a/40706065

Looking good though. I don't really care if the tests are failing, so I'll just approve. Just as info.

**Pull request merged**
